# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('image_url', models.CharField(max_length=1024)),
                ('food_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='FoodPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('NOT_CHECKED', 'NOT_CHECKED'), ('CHECKED', 'CHECKED')], default='NOT_CHECKED', max_length=16)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tensorflow_backend.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, null=True, unique=True)),
                ('prob', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS')], default='PENDING', max_length=16)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('response_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image_url', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('start_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SessionPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tensorflow_backend.Person')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tensorflow_backend.Session')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tensorflow_backend.Person'),
        ),
        migrations.AddField(
            model_name='image',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tensorflow_backend.Session'),
        ),
        migrations.AddField(
            model_name='foodperson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tensorflow_backend.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionperson',
            unique_together=set([('person', 'session')]),
        ),
    ]
