# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tensorflow_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='full_name',
            field=models.CharField(default='', max_length=2014),
        ),
    ]
